name: docker-build-push

on:
  push:
    branches: [main]
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'Dockerfile*'
      - '.github/workflows/docker-deploy.yml'

jobs:
  build-push-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_PREFIX: ${{ github.repository }}
      TRIVY_CACHE_DIR: /root/.cache/trivy

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🏗️ Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🧱 Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ♻️ Restore Trivy vulnerability DB cache
      - name: ♻️ Restore Trivy cache
        id: trivy-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.TRIVY_CACHE_DIR }}
          key: trivy-db-${{ runner.os }}-v1

      # ---------------- Build & Push API ----------------
      - name: 📦 Build & push API image
        id: build_api
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/api:${{ github.sha }}
          cache-from: type=gha,scope=api
          cache-to: type=gha,scope=api,mode=max

      - name: 🔍 Trivy Scan API (HIGH/CRITICAL blocker)
        uses: aquasecurity/trivy-action@0.15.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/api:${{ github.sha }}
          format: table
          exit-code: '1'
          vuln-type: os,library
          severity: CRITICAL,HIGH
          cache-dir: ${{ env.TRIVY_CACHE_DIR }}

      # ---------------- Build & Push Web ----------------
      - name: 📦 Build & push Web image
        id: build_web
        uses: docker/build-push-action@v5
        with:
          context: ./apps/web
          file: ./apps/web/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/web:${{ github.sha }}
          cache-from: type=gha,scope=web
          cache-to: type=gha,scope=web,mode=max

      - name: 🔍 Trivy Scan Web (HIGH/CRITICAL blocker)
        uses: aquasecurity/trivy-action@0.15.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/web:${{ github.sha }}
          format: table
          exit-code: '1'
          vuln-type: os,library
          severity: CRITICAL,HIGH
          cache-dir: ${{ env.TRIVY_CACHE_DIR }}

      # 💾 Save Trivy cache (if updated)
      - name: 💾 Save Trivy cache
        if: steps.trivy-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: ${{ env.TRIVY_CACHE_DIR }}
          key: trivy-db-${{ runner.os }}-v1

      - name: 🏷️ Summary
        run: |
          echo "Images pushed & scanned:"
          echo "  $REGISTRY/$IMAGE_PREFIX/api:${GITHUB_SHA} (Trivy passed)"
          echo "  $REGISTRY/$IMAGE_PREFIX/web:${GITHUB_SHA} (Trivy passed)"
